name: common_backend
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  dart_appwrite: 16.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
